name: 💼 Commercial Inquiry
description: Questions about commercial use, licensing, or enterprise features
title: "[COMMERCIAL] "
labels: ["commercial", "business"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Interested in commercial use of Vectorpenter? Let's discuss! 💼
        
        **For immediate commercial support:** Contact us directly at [your-email]

  - type: dropdown
    id: inquiry_type
    attributes:
      label: Inquiry Type
      description: What type of commercial inquiry is this?
      options:
        - Commercial License
        - Enterprise Support
        - Custom Development
        - Training & Consulting
        - Managed Hosting
        - Partnership Opportunity
        - Pricing Information
        - Other
    validations:
      required: true

  - type: textarea
    id: organization
    attributes:
      label: Organization Details
      description: Tell us about your organization
      placeholder: |
        - Company name and size
        - Industry
        - Use case overview
        - Geographic location

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: What are your specific needs?
      placeholder: |
        - Number of users/developers
        - Expected data volume
        - Performance requirements
        - Integration needs
        - Compliance requirements

  - type: dropdown
    id: timeline
    attributes:
      label: Timeline
      description: When do you need this?
      options:
        - "Immediate (within 1 month)"
        - "Short term (1-3 months)"
        - "Medium term (3-6 months)"
        - "Long term (6+ months)"
        - "Just exploring options"

  - type: dropdown
    id: budget
    attributes:
      label: Budget Range (Optional)
      description: What's your approximate budget range?
      options:
        - "Under $10k"
        - "$10k - $50k"
        - "$50k - $100k"
        - "$100k - $500k"
        - "$500k+"
        - "Prefer not to disclose"

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Anything else you'd like us to know?
      placeholder: "Special requirements, questions, or context..."

  - type: input
    id: contact
    attributes:
      label: Preferred Contact Method
      description: How should we reach you?
      placeholder: "email@company.com or LinkedIn profile"
    validations:
      required: true

  - type: checkboxes
    id: consent
    attributes:
      label: Consent
      options:
        - label: I consent to being contacted about this inquiry
          required: true
        - label: I'm authorized to make inquiries on behalf of my organization
          required: true
